import twig, {
	extendFunction,
	extendFilter,
	extendTag,
} from '../index';

describe('extension', () => {
	it('should be extendable with functions', () => {
		var template = twig({
			'data': `extend {{ reverseFunction('function') }}`,
		});
		
		extendFunction('reverseFunction', (value) => value.split('').reverse().join(''));
		var promise = template
			.render()
			.then((dom) => dom.text());
		
		return expect(promise).to.eventually.equal('extend noitcnuf');
	});
	
	it('should be extendable with filters', () => {
		var template = twig({
			'data': `extend {{ 'filter'|reverseFilter }}`,
		});
		
		extendFilter('reverseFilter', (value) => value.split('').reverse().join(''));
		var promise = template
			.render()
			.then((dom) => dom.text());
		
		return expect(promise).to.eventually.equal('extend retlif');
	});
	
	it('should be extendable with tags', () => {
		extendTag({
			'type': 'extendedTag',
			'open': true,
			'next': [],
			'regex': /^extendedTag/,
			'parse': () => ({
				'chain': false,
				'output': 'generated by extended tag',
			}),
		});
		
		var template = twig({
			'data': `{% extendedTag %}`,
		});
		
		var promise = template
			.render()
			.then((dom) => dom.text());
		
		return expect(promise).to.eventually.equal('generated by extended tag');
	});
});
